---
- name: Check global ports
  wait_for:
    host: "{{ item.hostname }}"
    port: "{{ item.port | default('80') }}"
    state: started         # Port should be open
    delay: 0               # No wait before first check (sec)
    timeout: 3             # Stop checking after timeout (sec)
  ignore_errors: true
  with_items: "{{ addresses }}"
  register: message

