---
driver:
#  name: dokken
  name: docker

provisioner:
  name: ansible_playbook
#  roles_path: ./roles
  hosts: localhost
  require_ansible_repo: true
  ansible_verbose: true
  ansible_version: latest
  additional_ssh_private_keys:
  - ~/.ssh/id_rsa
  playbook: connectivity.yml
  ansible_cfg_path: ./ansible.cfg

platforms:
  - name: ubuntu-20.04

suites:
  - name: default
    run_list:
    attributes:
